version: "3.7"

services:
  kasm:
    container_name: kasm
    privileged: true
    environment:
        DOCKER_HUB_PASSWORD: PASS
        DOCKER_HUB_USERNAME: USER
        DOCKER_MTU: 1500
        KASM_PORT: 3000
        APP_HOST: cloudrack-kasm_1
        APP_PORT: 3000
        PROXY_AUTH_ADD: "true"
    image: lscr.io/linuxserver/kasm:latest
    user: "991:991"
    ports:
      - target: 3000
        published: "3000"
        protocol: tcp
      - target: 443
        published: "443"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/data:/opt
      - /DATA/AppData/$AppID/profiles:/profiles
