version: "3.7"

services:
  kasm:
    container_name: kasm
    environment:
      - DOCKER_HUB_PASSWORD=PASS
      - DOCKER_HUB_USERNAME=USER
      - DOCKER_MTU=1500
      - KASM_PORT=443
    image: lscr.io/linuxserver/kasm:latest
    labels:
      icon: https://i.ibb.co/JqVkFv4/image.png
    ports:
      - target: 3000
        published: "3022"
        protocol: tcp
      - target: 443
        published: "443"
        protocol: tcp
    privileged: true
    restart: unless-stopped
    volumes:
      - /DATA/AppData/kasm/data:/opt
      - /DATA/AppData/cloudrack-kasm/profiles:/profiles
    devices: []
    cap_add: []
    command: []
    networks:
      - kasm
    cpu_shares: 90
    deploy:
      resources:
        limits:
          memory: 15973M
networks:
  kasm:
    name: kasm
