version: "2.1"
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - APP_HOST=kasm
      - APP_PORT=3000
      - PROXY_AUTH_ADD="false"
      - TITLE=cloudrack-kasm
      - KASM_PORT=443
      - DOCKER_HUB_USERNAME=USER #optional
      - DOCKER_HUB_PASSWORD=PASS #optional
      - DOCKER_MTU=1500 #optional
    ports:
      - 3000:3000
      - 443:443
    restart: unless-stopped
