version: "3.7"

services:

  kasm:
    image: lscr.io/linuxserver/kasm:latest
    user: "root"
    restart: unless-stopped
    privileged: true
    security_opt:
      - apparmor:unconfined
      - "label:disable"

    environment:
      DOCKER_HUB_PASSWORD: PASS
      DOCKER_HUB_USERNAME: USER
      DOCKER_MTU: 1500
      KASM_PORT: 3000
      APP_HOST: umbrel.local
      APP_PORT: 3000
      PROXY_AUTH_ADD: "true"
      PROXY_AUTH_WHITELIST: "/api/*"
      TITLE: cloudrack-kasm

    volumes:
      - type: volume
        source: kasm_opt
        target: /opt
      - type: volume
        source: kasm_profiles
        target: /profiles
      - type: volume
        source: kasm_dev_input
        target: /dev/input
      - type: volume
        source: kasm_run_udev_data
        target: /run/udev/data
      - type: bind
        source: /sys/kernel/security
        target: /sys/kernel/security
        read_only: true

    networks:
      kasm:

    ports:
      - target: 3000
        published: "3000"
        protocol: tcp
      - target: 443
        published: "443"
        protocol: tcp

    # Remove the OpenTelemetry tracing processor
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  tmpfs:
    image: alpine
    command: sh -c "sleep 9999999999d"
    volumes:
      - type: tmpfs
        target: /tmpfs
        tmpfs:
          size: 100m

networks:
  kasm:

volumes:
  kasm_opt:
  kasm_profiles:
  kasm_dev_input:
  kasm_run_udev_data:
