version: "3.7"

services:

  kasm:
    container_name: kasm # added line
    image: lscr.io/linuxserver/kasm:latest
    restart: unless-stopped
    privileged: "true"
    environment:
      DOCKER_HUB_PASSWORD: PASS
      DOCKER_HUB_USERNAME: USER
      DOCKER_MTU: 1500
      KASM_PORT: 443
      APP_HOST: https://umbrel.local
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"
      TITLE: cloudrack-kasm
      KASM_STORAGE_PATH: /opt
      KASM_PROFILE_STORAGE_PATH: /profiles
      KASM_GAMEPAD_INPUT_PATH: /dev/input
      KASM_UDEV_DATA_PATH: /run/udev/data

    volumes:
      - /path/to/data:/opt
      - /path/to/profiles:/profiles #optional
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    # - /var/run/docker.sock:/var/run/docker.sock #optional

    ports:
      - target: 3000
        published: "3000"
        protocol: tcp
        mode: host
      - target: 443
        published: "443"
        protocol: tcp
        mode: host

    # Remove the privileged flag and add the following line to disable AppArmor
    security_opt:
      - apparmor:unconfined

networks:
  kasm:
