version: "3.7"

services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    user: 1000:1000
    restart: unless-stopped
    environment:
      DOCKER_HUB_PASSWORD: PASS
      DOCKER_HUB_USERNAME: USER
      DOCKER_MTU: 1500
      KASM_PORT: 8444
      APP_HOST: cloudrack-kasm_kasm_1
      APP_PORT: 3022
      PROXY_AUTH_ADD: "true"
    volumes:
      - data:/opt
      - profiles:/profiles
    restart: unless-stopped
    ports:
      - 8444:443
      - 3022:3000

volumes:
  data:
  profiles:
