version: "3.7"

services:

  kasm:
    image: lscr.io/linuxserver/kasm:latest
    user: "root"
    restart: unless-stopped

    environment:
      DOCKER_HUB_PASSWORD: PASS
      DOCKER_HUB_USERNAME: USER
      DOCKER_MTU: 1500
      KASM_PORT: 443
      APP_HOST: umbrel.local
      APP_PORT: 443
      PROXY_AUTH_ADD: "true"
      PROXY_AUTH_WHITELIST: "/api/*"
      TITLE: cloudrack-kasm

    volumes:
      - type: bind
        source: /${APP_DATA_DIR}/DATA/AppData/kasm/opt
        target: /opt
      - type: bind
        source: /${APP_DATA_DIR}/DATA/AppData/kasm/profiles
        target: /profiles
      - type: bind
        source: /${APP_DATA_DIR}/dev/input
        target: /dev/input
      - type: bind
        source: /${APP_DATA_DIR}/run/udev/data
        target: /run/udev/data
    networks:
      - kasm

    ports:
      - target: 3000
        published: "3000"
        protocol: tcp
      - target: 443
        published: "443"
        protocol: tcp

networks:
  kasm:
    name: kasm
