version: "3.7"

services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    user: 1000:1000
    restart: unless-stopped
    environment:
      DOCKER_HUB_PASSWORD: PASS
      DOCKER_HUB_USERNAME: USER
      DOCKER_MTU: 1500
      KASM_PORT: 443
      APP_HOST: cloudrack-kasm_kasm_1
      APP_PORT: 443
      PROXY_AUTH_ADD: "false"
    volumes:
      - ${APP_DATA_DIR}/cloudrack-kasm-data:/opt
      - ${APP_DATA_DIR}/cloudrack-kasm-profiles:/profiles
    restart: unless-stopped
    networks:
      - kasm
    ports:
      - target: 3000
        published: "3022"
        protocol: tcp
      - target: 443
        published: "443"
        protocol: tcp
networks:
  kasm:
    name: kasm
