version: "3.7"

services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      DOCKER_HUB_PASSWORD: PASS
      DOCKER_HUB_USERNAME: USER
      DOCKER_MTU: 1500
      KASM_PORT: 443
      APP_HOST: cloudrack-kasm_kasm_1
      APP_PORT: 443
      PROXY_AUTH_ADD: "true"
      PROXY_AUTH_WHITELIST: "/api/*"
    volumes:
      - ${APP_DATA_DIR}/cloudrack-kasm-data:/opt
      - ${APP_DATA_DIR}/cloudrack-kasm-profiles:/profiles
    networks:
      - kasm
    ports:
      - target: 3000
        published: "3000"
        protocol: tcp
      - target: 443
        published: "443"
        protocol: tcp
networks:
  kasm:
    name: kasm
