version: "3.7"

services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    user: root
    restart: unless-stopped
    environment:
      DOCKER_HUB_PASSWORD: PASS
      DOCKER_HUB_USERNAME: USER
      DOCKER_MTU: 1500
      KASM_PORT: 443
      APP_HOST: cloudrack-kasm_kasm_1
      APP_PORT: 443
      PROXY_AUTH_ADD: "false"
    volumes:
      - type: bind
        source: /DATA/AppData/cloudrack-kasm/data
        target: /opt
      - type: bind
        source: /DATA/AppData/cloudrack-kasm/profiles
        target: /profiles
    restart: unless-stopped
    ports:
      - target: 3000
        published: "3022"
        protocol: tcp
      - target: 443
        published: "443"
        protocol: tcp
volumes:
  data:
  profiles:
