version: '3.3'

services:
  
  plesk:
    image: plesk/plesk
    environment:
       APP_HOST: cloudrack-plesk_plesk_1
       APP_PORT: 8880
       PROXY_AUTH_ADD: "false"
       PROXY_AUTH_WHITELIST: "/api/*"
       TITLE: cloudrack-plesk
       CONTAINER_NAME: name
       tmpfs: '/tmp,/run,/run/lock'
    ports:
      - '8540:80'
      - '4463:443'
      - '8880:8880'
      - '8223:8443'
      - '8447:8447'
      - '3332:21'
      - '3844:3306'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
