version: "3.7"

services:

  kasm:
    image: lscr.io/linuxserver/kasm:latest
    user: "root"
    restart: unless-stopped
    privileged: true
    security_opt:
      - apparmor:unconfined
      - "label:disable"
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      KASM_PORT: 443
      DOCKER_HUB_USERNAME: USER #optional
      DOCKER_HUB_PASSWORD: PASS #optional
      DOCKER_MTU: 1500 #optional
      APP_HOST: umbrel.local
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"
      PROXY_AUTH_WHITELIST: "/api/*"
      TITLE: cloudrack-kasm
    volumes:
      - /DATA/AppData/kasmweb/data:/opt
      - /DATA/AppData/profiles:/profiles #optional
      - DATA/AppData/dev/input:/dev/input #optional
      - DATA/AppData/run/udev/data:/run/udev/data #optional
    ports:
      - 3000:3000
      - 443:443
    restart: unless-stopped
tmpfs:
    image: alpine
    command: sh -c "sleep 9999999999d"
    volumes:
      - type: tmpfs
        target: /tmpfs
        tmpfs:
          size: 1g