version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: cloudrack_wordpress_1
      APP_PORT: 8088
      PROXY_AUTH_ADD: "false"
    image: wordpress
    user: 1000:1000
    init: true
    restart: on-failure
    stop_grace_period: 1m
    healthcheck:
      disable: true
