version: "3.7"

services:
  wordpress:
    image: wordpress
    user: 1001:1001
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      APP_HOST: cloudrack-wordpress_app_proxy_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"
    volumes:
      - wordpress:/var/www/html
      - themes:/var/www/html/wp-content/themes
      - plugins:/var/www/html/wp-content/plugins
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
volumes:
  wordpress:
  db:
  themes:
  plugins:
